apiVersion: v1
kind: ConfigMap
metadata:
  name: example-paper-config
  namespace: example-paper
data:
  server.properties: |
    server-port=25565
    motd=A Minecraft Server on k8s
    max-players=20
    online-mode=false
