apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-paper-gateway
  namespace: example-paper
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: minecraft
      protocol: TCP
      port: 30000
