apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-paper-route
  namespace: example-paper
spec:
  parentRefs:
    - name: example-paper-gateway
  rules:
    - backendRefs:
        - name: example-paper
          port: 25565
